{{- include "shared.configMap" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gg-env-file
  labels:
    lacework.net/service_owner: data-platform
stringData:
  fileContents: |-
{{- range $key, $val := $.Values.configMap.dataAutoGen }}
    {{ $key }}={{ $val }}
{{- end }}
